fm_elfinder:
    instances:
        default:
            locale: fr
            editor: ckeditor
            fullscreen: true
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/images

