<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6xa6qzv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6xa6qzv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6xa6qzv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6xa6qzv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6xa6qzv\App_KernelDevDebugContainer([
    'container.build_hash' => '6xa6qzv',
    'container.build_id' => '905615f3',
    'container.build_time' => 1585853959,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6xa6qzv');
