<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCELiFwB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCELiFwB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCELiFwB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCELiFwB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCELiFwB\App_KernelDevDebugContainer([
    'container.build_hash' => 'CELiFwB',
    'container.build_id' => '74a474d8',
    'container.build_time' => 1585593343,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCELiFwB');
