<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDCgRJHF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDCgRJHF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDCgRJHF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDCgRJHF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDCgRJHF\App_KernelDevDebugContainer([
    'container.build_hash' => 'DCgRJHF',
    'container.build_id' => '2f3222c1',
    'container.build_time' => 1585650292,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDCgRJHF');
